Training with a single process on 1 device (cuda:0).
WARNING: No pretrained configuration specified for MONet_T_2 model. Using a default. Please add a config to the model pretrained_cfg registry or pass explicitly.
Model MONet_T_2 created, param count:881870
Data processing configuration for current model + dataset:
	input_size: (3, 32, 32)
	interpolation: bicubic
	mean: (0.485, 0.456, 0.406)
	std: (0.229, 0.224, 0.225)
	crop_pct: 0.875
	crop_mode: center
AMP not enabled. Training in float32.
ERROR: No checkpoint found at '/home/sharipov/monet/output/train/Upd_Exp1_CIFAR10_2_layer/checkpoint-261.pth.pth.tar'
Traceback (most recent call last):
  File "/home/sharipov/monet/train.py", line 1083, in <module>
    main()
  File "/home/sharipov/monet/train.py", line 551, in main
    resume_epoch = resume_checkpoint(
  File "/home/sharipov/monet/timm/models/_helpers.py", line 148, in resume_checkpoint
    raise FileNotFoundError()
FileNotFoundError
[2024-03-26 11:39:11,112] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 949243) of binary: /home/sharipov/monet/venv/bin/python
Traceback (most recent call last):
  File "/home/sharipov/monet/venv/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/sharipov/monet/venv/lib64/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/sharipov/monet/venv/lib64/python3.9/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/home/sharipov/monet/venv/lib64/python3.9/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/sharipov/monet/venv/lib64/python3.9/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/sharipov/monet/venv/lib64/python3.9/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-26_11:39:11
  host      : i36.izar.cluster
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 949243)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
