Training with a single process on 1 device (cuda:0).
WARNING: No pretrained configuration specified for MONet_T_one model. Using a default. Please add a config to the model pretrained_cfg registry or pass explicitly.
Model MONet_T_one created, param count:876396
Data processing configuration for current model + dataset:
	input_size: (3, 32, 32)
	interpolation: bicubic
	mean: (0.485, 0.456, 0.406)
	std: (0.229, 0.224, 0.225)
	crop_pct: 0.875
	crop_mode: center
AMP not enabled. Training in float32.
/home/sharipov/monet/venv/lib64/python3.9/site-packages/torch/utils/data/dataloader.py:558: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Scheduled epochs: 300. LR stepped per epoch.
Train: 0 [   0/625 (  0%)]  Loss: 2.30 (2.30)  Time: 1.412s,   45.32/s  (1.412s,   45.32/s)  LR: 1.000e-05  Data: 0.956 (0.956)
Train: 0 [  50/625 (  8%)]  Loss: 2.28 (2.30)  Time: 0.020s, 3278.00/s  (0.054s, 1182.40/s)  LR: 1.000e-05  Data: 0.015 (0.039)
Train: 0 [ 100/625 ( 16%)]  Loss: 2.23 (2.28)  Time: 0.024s, 2614.04/s  (0.042s, 1532.51/s)  LR: 1.000e-05  Data: 0.020 (0.032)
Train: 0 [ 150/625 ( 24%)]  Loss: 2.23 (2.27)  Time: 0.015s, 4221.41/s  (0.038s, 1699.32/s)  LR: 1.000e-05  Data: 0.010 (0.029)
Train: 0 [ 200/625 ( 32%)]  Loss: 2.20 (2.26)  Time: 0.041s, 1548.28/s  (0.036s, 1791.35/s)  LR: 1.000e-05  Data: 0.036 (0.028)
Train: 0 [ 250/625 ( 40%)]  Loss: 2.26 (2.25)  Time: 0.014s, 4518.66/s  (0.034s, 1856.28/s)  LR: 1.000e-05  Data: 0.009 (0.028)
Train: 0 [ 300/625 ( 48%)]  Loss: 2.19 (2.24)  Time: 0.042s, 1533.68/s  (0.034s, 1901.39/s)  LR: 1.000e-05  Data: 0.037 (0.027)
Train: 0 [ 350/625 ( 56%)]  Loss: 2.22 (2.24)  Time: 0.024s, 2613.63/s  (0.033s, 1938.59/s)  LR: 1.000e-05  Data: 0.020 (0.027)
Train: 0 [ 400/625 ( 64%)]  Loss: 2.12 (2.23)  Time: 0.042s, 1541.38/s  (0.033s, 1963.20/s)  LR: 1.000e-05  Data: 0.037 (0.026)
Train: 0 [ 450/625 ( 72%)]  Loss: 2.20 (2.23)  Time: 0.030s, 2130.76/s  (0.032s, 1986.95/s)  LR: 1.000e-05  Data: 0.025 (0.026)
Train: 0 [ 500/625 ( 80%)]  Loss: 2.22 (2.22)  Time: 0.052s, 1238.21/s  (0.032s, 2002.29/s)  LR: 1.000e-05  Data: 0.047 (0.026)
Train: 0 [ 550/625 ( 88%)]  Loss: 2.23 (2.22)  Time: 0.005s, 12407.46/s  (0.032s, 2020.96/s)  LR: 1.000e-05  Data: 0.000 (0.026)
Train: 0 [ 600/625 ( 96%)]  Loss: 2.18 (2.21)  Time: 0.084s,  763.75/s  (0.032s, 2028.46/s)  LR: 1.000e-05  Data: 0.079 (0.026)
Test: [   0/156]  Time: 1.250 (1.250)  Loss:   2.038 ( 2.038)  Acc@1:  26.562 ( 26.562)  Acc@5:  84.375 ( 84.375)
Test: [  50/156]  Time: 0.010 (0.034)  Loss:   2.093 ( 2.062)  Acc@1:  15.625 ( 23.162)  Acc@5:  78.125 ( 79.565)
Test: [ 100/156]  Time: 0.009 (0.022)  Loss:   1.965 ( 2.060)  Acc@1:  28.125 ( 23.113)  Acc@5:  87.500 ( 79.981)
Test: [ 150/156]  Time: 0.002 (0.018)  Loss:   2.055 ( 2.057)  Acc@1:  25.000 ( 23.448)  Acc@5:  81.250 ( 79.708)
Test: [ 156/156]  Time: 0.039 (0.017)  Loss:   2.123 ( 2.057)  Acc@1:  18.750 ( 23.540)  Acc@5:  68.750 ( 79.680)
Traceback (most recent call last):
  File "/home/sharipov/monet/train.py", line 1207, in <module>
    main()
  File "/home/sharipov/monet/train.py", line 937, in main
    utils.update_summary(
TypeError: update_summary() got an unexpected keyword argument 'additional_metrics'
[2024-04-13 20:53:21,309] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 1570916) of binary: /home/sharipov/monet/venv/bin/python
Traceback (most recent call last):
  File "/home/sharipov/monet/venv/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/sharipov/monet/venv/lib64/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/sharipov/monet/venv/lib64/python3.9/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/home/sharipov/monet/venv/lib64/python3.9/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/sharipov/monet/venv/lib64/python3.9/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/sharipov/monet/venv/lib64/python3.9/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-04-13_20:53:21
  host      : i12.izar.cluster
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1570916)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
