Training with a single process on 1 device (cuda:0).
WARNING: No pretrained configuration specified for MONet_T model. Using a default. Please add a config to the model pretrained_cfg registry or pass explicitly.
Model MONet_T created, param count:10148366
Data processing configuration for current model + dataset:
	input_size: (3, 32, 32)
	interpolation: bicubic
	mean: (0.485, 0.456, 0.406)
	std: (0.229, 0.224, 0.225)
	crop_pct: 0.875
	crop_mode: center
AMP not enabled. Training in float32.
Restoring model state from checkpoint...
Restoring optimizer state from checkpoint...
Loaded checkpoint '/home/sharipov/monet/output/train/Exp1_CIFAR10/model_best.pth.tar' (epoch 9)
Traceback (most recent call last):
  File "/home/sharipov/monet/train.py", line 1083, in <module>
    main()
  File "/home/sharipov/monet/train.py", line 589, in main
    dataset_train = create_dataset(
  File "/home/sharipov/monet/timm/data/dataset_factory.py", line 185, in create_dataset
    ds = ImageDataset(root, reader=name, class_map=class_map, load_bytes=load_bytes, **kwargs)
  File "/home/sharipov/monet/timm/data/dataset.py", line 35, in __init__
    reader = create_reader(
  File "/home/sharipov/monet/timm/data/readers/reader_factory.py", line 34, in create_reader
    reader = ReaderImageFolder(root, **kwargs)
  File "/home/sharipov/monet/timm/data/readers/reader_image_folder.py", line 73, in __init__
    raise RuntimeError(
RuntimeError: Found 0 images in subfolders of /home/sharipov/monet/data/CIFAR10/cifar-10-batches-py. Supported image extensions are .png, .jpg, .jpeg
[2024-03-01 11:55:29,355] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 3114540) of binary: /home/sharipov/monet/venv/bin/python
Traceback (most recent call last):
  File "/home/sharipov/monet/venv/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/sharipov/monet/venv/lib64/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/sharipov/monet/venv/lib64/python3.9/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/home/sharipov/monet/venv/lib64/python3.9/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/sharipov/monet/venv/lib64/python3.9/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/sharipov/monet/venv/lib64/python3.9/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-01_11:55:29
  host      : i50.izar.cluster
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3114540)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
